version: "3.8"
services:
  postgres:
    build: .
    container_name: pg-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SomePassword
      - POSTGRES_DB=postgres
    ports:
      - 5555:5432
    networks:
      - pg-test
networks:
  pg-test:
