START TRANSACTION;

CREATE TABLE foos (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_foos PRIMARY KEY (id)
);

CREATE TABLE bars (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    foo_id integer NOT NULL,
    CONSTRAINT pk_bars PRIMARY KEY (id),
    CONSTRAINT fk_bars_foos_foo_id FOREIGN KEY (foo_id) REFERENCES foos (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_bars_foo_id ON bars (foo_id);

COMMIT;